### PR TITLE
LALR analysis performance improvement

### PR DESCRIPTION
**Pull request by jmishra01**
Use dictionary comprehension to improve performance of lalr analysis.

### CODE REVIEW

**Comment by MegaIng** [comment]
What is the performance improvement of this? I.e. what is the measurable increase?

**Comment by erezsh** [comment]
@jmishra01 Generally, when creating a PR claiming to provide a speed improvement, you should also provide some evidence that it is indeed the case. At the very least, the numerical results of your benchmark with and without this single change.

I think this change is a bit cleaner, so I'm inclined to accept it. But I'm not convinced it's actually faster.

**Comment by jmishra01** [comment]
@erezsh Understood! 
Please check attached image.
List or dictionary comprehension always faster than normal loop method.

image

**Comment by MegaIng** [comment]
But what is the impact on the whole of lark? Isolated pieces of code can be optimized to an absurd amount without actually improving anything in practice (in your example, `dict.fromkeys` would probably be faster still)

**Comment by erezsh** [comment]
If we rename the PR to "style improvements for code", can we agree it's acceptable?

**Comment by erezsh** [comment]
Also @jmishra01 please flatten this to one single commit.

**Comment by MegaIng** [comment]
For style I would also prefer `dict.fromkeys(X, 0)` instead of `dict(zip(X, [0]*len(X)))`. But yes, otherwise it's fine.

**Comment by jmishra01** [comment]
> @jmishra01 Looks like a sync issue. Make sure to fetch and rebase over the latest master.

Kindly review again.

**Comment by erezsh** [comment]
@jmishra01 I agree with @MegaIng that `dict.fromkeys(X, 0)` is the best of the 3 versions.

**Pull request closed without merging**
