### PR TITLE
Rebased + Corrected + Improved on PR #973

### PR DESCRIPTION
**Pull request by erezsh**
Main changes -

- Rebased the many commits into a few
- Edited the docstring + added merge_transformer to docs 
- Edited the example to allow both CSV and JSON in the same file; moved it into a separate folder (`examples/composition`)

### CODE REVIEW

**Review by MegaIng — APPROVED** [review]

**Comment by Drvanon** [comment]
It looks really cool! I think the documentation is a lot more descriptive than what I had.

**Comment by erezsh** [comment]
@Drvanon Just created release 0.12.0, which includes `merge_transformers`.

**Comment by Fokko** [comment]
Hey @erezsh wondering when it will be released to pypi: https://pypi.org/project/lark/#history 👍🏻

**Comment by erezsh** [comment]
Hi @Fokko, it's there now!

**Pull request merged**
