### PR TITLE
Changed indentation and blockcodes.

### PR DESCRIPTION
**Pull request by Patitotective**
Replaced indentation code blocks to use \`\`\` and removed indentation on lark (grammar) code blocks.

### CODE REVIEW

**Comment by MegaIng** [comment]
Why?

**Comment by Patitotective** [comment]
For me it is clearer having those \`\`\` and in the first code block the syntax highlight wasn't working, now it does.   
In lark grammar code blocks there were indentation before each line which made you remove them when you copy it.

**Comment by MegaIng** [comment]
The problem is that fenced code blocks are generally less supported, since they aren't as old as intended code blocks and instead a somewhat common extension. But it's probably fine.

**Comment by erezsh** [comment]
Sorry, I don't see the value in this PR.

I hope that won't dissuade you from future contributions.

**Comment by Patitotective** [comment]
I understand :upside_down_face:
Thanks for taking the time to reply me. :+1:

**Pull request closed without merging**
