### PR TITLE
Add ConfigurationError

### PR DESCRIPTION
**Pull request by ThatXliner**
See https://gitter.im/lark-parser/Lobby?at=5fb988980451324f1529bf51

### CODE REVIEW

**Comment by ThatXliner** [comment]
about the broken test, I thought we deprecated 2.7

**Comment by MegaIng** [comment]
Please undo all changes that aren't relevant to this PR, e.g. all refactoring. It makes checking this PR a lot harder, and we already established that we want that (if at all) in another PR.

**Comment by ThatXliner** [comment]
sorry!

**Comment by erezsh** [comment]
Thanks @ThatXliner !

I just implemented it in #779 , so I'm closing this.

Let me know if there's anything missing or misplaced.

**Pull request closed without merging**
