### PR TITLE
Method iter_subtrees_topdown added

### PR DESCRIPTION
**Pull request by worldmind**
I am not a big hacker, but looks working

### CODE REVIEW

**Comment by erezsh** [comment]
Hi, looks like a good start!

For a method that is part of the core tree class, it's a good idea to add a unit-test. For example, in `tests/test_trees.py`

Also, I believe the `if` at the start of the method is unnecessary?

**Comment by worldmind** [comment]
> it's a good idea to add a unit-test

yes, I think same, but not found tests for `iter_subtrees` and did not do, I make it later, maybe tomorrow.

> I believe the if at the start of the method is unnecessary?

yes, agree, I will remove it

**Comment by worldmind** [comment]
@erezsh why you use unittest module? As for me it so unpythonic, maybe I can make new test with pytest? It can [run unittests tests](https://docs.pytest.org/en/latest/unittest.html).

**Comment by erezsh** [comment]
Is there really such a difference? I prefer not to add a new dependency unless there's a good reason (right now Lark has no dependencies at all, except for optional support for Nearley).

**Comment by worldmind** [comment]
I can not say that is so important, I just like write beautiful code without no needed boilerplate text.
I push some simple test.

**Comment by worldmind** [comment]
Maybe I will try squash three commits to one?

**Comment by erezsh** [comment]
Looks good. Thanks!

**Comment by worldmind** [comment]
Thanks for your project!

**Pull request merged**
