### PR TITLE
Add support for çğıöşü charatchers

### PR DESCRIPTION
**Pull request by midnio**
There is no fucking Turkish char support. I just added it.

### CODE REVIEW

**Comment by BTaskaya** [comment]
It is not compatible with Python2.7. Make tests before submitting PRs

**Comment by erezsh** [comment]
There is support for unicode, just not as part of the common grammar.

I would accept a PR that adds support for all languages, not just Turkish.

**Comment by midnio** [comment]
That will take, long.

**Comment by midnio** [comment]
@erezsh I'll send other PR's for other languages, is it valid?

**Comment by midnio** [comment]
@erezsh i'll try for giving regexp idea! thanks

**Comment by midnio** [comment]
#273

**Pull request closed without merging**
