### PR TITLE
Update JSON Tutorial Code for Python 3

### PR DESCRIPTION
**Pull request by copperlight**
Thanks for writing such a helpful tutorial!

The existing code snippets which demonstrate the Transformer class rely
on tuple parameter unpacking, which was removed as of PEP-3113, which
landed in Python 3.0.

https://www.python.org/dev/peps/pep-3113/

The class methods don't make use of any internal data, so they can be
marked with @staticmethod.

The updated versions of these code snippets continue to work as expected
in Python 2.7.16, noting the difference in how unicode strings are
marked.

The code snippets copy and paste cleanly into the Python repl.

### CODE REVIEW

**Comment by erezsh** [comment]
Thank you for the update.

Regarding the tuple unpacking, Lark provides a utility for that  `@v_args(inline=True)`.

I think it's more readable, so it'd be great If you could use that instead.

**Comment by copperlight** [comment]
Updated examples to use the `@v_args` decorator.

Updated the benchmark example at the bottom.

Verified copy-paste in both the Python 3.7.3 and 2.7.16 repls.

**Comment by drunkwcodes** [comment]
Does it mean that rename `v_args(inline=True)` and use `@inline` decorator instead?

**Comment by copperlight** [comment]
@erezsh What do you think of the changes?

The `TreeToJson` transformer could be made more brief, by doing the following:

```
null = None
true = True
false = False
```

However, I am not sure if this helps or hinders understanding.

**Comment by erezsh** [comment]
The changes are good, but the code is a little verbose. After all, this is supposed to be a tutorial for beginners, so being clear and simple is very important, especially in the code. I'll have a look at it soon.

**Pull request closed without merging**
