### PR TITLE
Fix #548

### LINKED ISSUE #548: AssertionError when packaging with pyinstaller
For some reason, any program using lark will crash with an assertionerror when it is frozen. Am I supposed to use a different packaging tool or something? Can you help?
Thanks in advance.

### PR DESCRIPTION
**Pull request by zurgeg**
This closes #548 by importing the *.larks into the final package in PyInstaller.

### CODE REVIEW

**Comment by MegaIng** [comment]
No it doesn't. PyInstaller will not find this package.

**Comment by zurgeg** [comment]
Ok, hold on. I'm making some changes to this PR that would actually fix it.

**Comment by zurgeg** [comment]
Ok, now the user can put a larkc.txt file containing `1` to have Lark autogenerate a ```lark-hook.py``` in the current directory.

**Comment by erezsh** [comment]
@zurgeg I admire your confidence in submitting such a PR.

And putting this at `lark.__init__`, what a madmen.

```python
hook = open('lark-hook.py','w')
```

However, that is not acceptable code for Lark. Please refrain from continuing this PR and let us resolve it in due course.

**Pull request closed without merging**
