### PR TITLE
Added missing binary files to .gitignore

### PR DESCRIPTION
**Pull request by evandrocoan**
There are a lot of these: 

image

### CODE REVIEW

**Comment by erezsh** [comment]
A .gitignore is important, but it shouldn't be part of a repo. Everyone has their own ideas of what git should ignore, and although everyone agrees on pyc files, it would still prevent contributors from choosing their own.

**Comment by evandrocoan** [comment]
I do not know what to say. `.gitignore` files configure your repo in helping the developer not adding accidental non-required/allowed files a binaries releases. Adding binary files is very bad for repository because they increase the repo size exponentially and to get rid of them later is involves a huge time/mess rewriting the whole git history.

I have the impression you are using `git-svn` to commit this repo, because your commit user name is like the ones I just did today when using `git-svn`. Then, may be you have a different ideia because of your experience with svn. In my opinion, I would just say that it is very bad not configuring a repository with the fully extent freedom git gives us. 

`git` is very different from the svn aspect of handling the ignored files. Even with files on a `.gitignore` file, you can commit them with `git add --force file_name.ignored`. The ignored files just do not go into the commit if you do not put the `--force` option. Then after that, they are just like any other file already committed. 

`.gitignore` files are not a dictatorship which enforces/forbids everybody from using the files. They are just a soft hint to the developers, saying, if you want to add these files to versioning, please, uses the `--force` argument. After that, you are free to change as much as you like the files are not in the `.gitignore`.

Then, adding `.gitignore` file is just helping new developers come in and get involved in the project, because as the project becomes more robust, it is easy to work with. With an inconvenience, I can work around the non-existence of `.gitignore` file, by individually marking the `.pyc` files as `Assume Unchanged` (thanks to git being feature rich). This just something inconvenient because everybody who forks and start working on this project would either risk living with the binary files, or apply this `Assume unchanged` file to everything.

**Comment by erezsh** [comment]
I use the regular git command line client. I haven't used svn in 10 years.

But following your slightly rude comment, I went and read suggested best practices, and it seems agreed upon that .gitignore should be part of the repo, so I'll allow it.

**Comment by evandrocoan** [comment]
It was not my intention to rude. I re-read my comment fixed some misspellings/grammars errors I could find. But could not find exactly were I was slightly rude (may be because I mentioned SVN?). I was just trying to expose my experience with git. Can you point out where you was slightly offended, so I can try to improve my manners.

Beyond that, I forgot to mention two things I consider important: 
1. As you said `Everyone has their own ideas of what git should ignore`, I agree that someone can think that their fork should have binaries, or would like to upload something ignored, and can have a great trouble trying to find out what happening, if they do not have a length experience with git. But for the ones who do not like the `.gitignore` thing, much easier would be for them to delete the `.gitignore` file once they clone the repository. They should have a habit to do so, because right now, because I do not know much repositories do not have `.gitignore`.
1. Once I have a great trouble with `.gitignore` files. So, I agree that they are not a bed of roses. I was trying to upload documentation with `doxygen`, but I had `*.png` on my `.gitignore` file. Then, when I updated the site to GitHub pages, it was very broken. Took me a quite few hours until I realize site was broken because the `.png` files were missing on the website, because they were not being added to git and being uploaded. After I realize that, took me some minutes until I realized I had added them to the `.gitignore` file.

> I use the regular git command line client

I think I will waist my time to recommend a Graphical User Interface I use for git, because you are a long time developer and uses the git by command line for so long, and probably is very used to it. Anyways, the name is [SmartGit](https://www.syntevo.com/smartgit/), it is available for Windows, Mac and Linux. It is a paid application, but you can use for free as long as you use it for non-profit or open-source coding. They cannot know whether you are using it for non-profit or not. They just ask you on installation and trust your answer. If you use it for paid-work, you can use it for a 30 days trial. I use SmartGit several years, but only for open source. But soon as I start working, I would by a license for it, because it is much more than git interface. See [SVN Integration](https://www.syntevo.com/smartgit/integrations/svn/),  [Distributed Reviews](https://www.syntevo.com/smartgit/distributed-reviews/) and [What it new](https://www.syntevo.com/smartgit/whats-new/)

**Comment by erezsh** [comment]
It's okay, no big deal.

It's not that you mentioned svn, but that you assumed something about me, and then went on for a few sentences as if that thing was true. In general, I think it's better to stick to facts, and opinions about technology, rather than the people who are discussing it.

Thanks for the recommendation, but I really don't find git complex or confusing. The CLI is definitely badly designed and counter-intuitive, but I'm used to it, and I just need the basic features most of the time anyway.

**Pull request merged**
