### PR TITLE
Add sphinx gallery so that docs are in examples

### PR DESCRIPTION
**Pull request by chsasank**
I was reading examples and thought it'd be nice if the examples are in the documentation
so adding them to docs using https://sphinx-gallery.github.io/stable/index.html.

- [x] Make sure build works fine. Gotta add requirement somewhere
- [x] Break examples so that there's a [subgallery for advanced](https://sphinx-gallery.github.io/stable/auto_examples/index.html?highlight=section)
- [x] Make examples execute

### CODE REVIEW

**Comment by chsasank** [comment]
How it looks

image

**Comment by erezsh** [comment]
Hmm a little puffy... can we turn it back into a list?

**Comment by chsasank** [comment]
Well there's the list on the sidebar. I don't know how to remove these thumbnails easily. :(

image

**Comment by erezsh** [comment]
Okay, I guess it's still better than before..

So is it ready for merge?

**Comment by chsasank** [comment]
Not ready yet. I'll let you know once it's ready.

There's an error with custom_lexer.py

```
(base) [~/test/omnidoc/lark/examples/advanced]$ python custom_lexer.py 
Traceback (most recent call last):
  File "custom_lexer.py", line 33, in <module>
    """, parser='lalr', lexer=TypeLexer)
  File "/Users/Sasank/miniconda3/lib/python3.6/site-packages/lark/lark.py", line 282, in __init__
    self.parser = self._build_parser()
  File "/Users/Sasank/miniconda3/lib/python3.6/site-packages/lark/lark.py", line 307, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, self.re, options=self.options)
  File "/Users/Sasank/miniconda3/lib/python3.6/site-packages/lark/parser_frontends.py", line 133, in __init__
    self.lexer = lexer_cls(lexer_conf, re_=re_)
TypeError: __init__() got an unexpected keyword argument 're_'
```

**Comment by MegaIng** [comment]
@chsasank Can not reproduce your error. Are you on the current master?

**Comment by chsasank** [comment]
> Can not reproduce your error. Are you on the current master?

I used release. I think you guys should put automatic CI on examples too.

I'll not try to fix the examples. So not gonna make them execute.

This PR is ready to merge post review

**Comment by MegaIng** [comment]
Is already fixed in master, just needs to be published.

**Comment by erezsh** [comment]
Oh right, the custom_lexer is a new addition, so it's not actually released yet.

**Comment by chsasank** [comment]
Of course something failed 🤦 . https://readthedocs.org/projects/lark-parser/builds/11695249/

**Comment by erezsh** [comment]
https://lark-parser.readthedocs.io/en/latest/examples/advanced/templates.html

SyntaxError??

**Comment by chsasank** [comment]
Umm wrong copy paste I guess. Gotta change in docs

**Pull request merged**
