### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BrandonBahret**
Added a section for conference talks.

I enjoy watching conference talks whenever I begin using new packages. It would be useful to create a list of such talks in the readme or elsewhere.

[Using Lark to Parse Text - Robin Reynolds-Haertle (PyCascades 2023)
](https://www.youtube.com/watch?v=CeOtqlh0UuQ)

### CODE REVIEW

**Review by MegaIng — APPROVED** [review]

**Review by erezsh — CHANGES_REQUESTED** [review]
Very cool. But I don't think that is the right place for the link.

Makes more sense to me to place it in the documentation: https://github.com/lark-parser/lark/blob/master/docs/index.rst

**Comment by MegaIng** [comment]
@erezsh I consider Readme a good idea since it's basically a project using Lark IMO. But also, we can link it in both places. It is also a decent tutorial.

**Comment by erezsh** [comment]
In what way is it a project? It looks like only a tutorial.

**Comment by erezsh** [comment]
Added link

**Pull request closed without merging**
