### PR TITLE
Adding one more project using Lark

### PR DESCRIPTION
**Pull request by napulen**

### CODE REVIEW

**Comment by napulen** [comment]
Holding on this PR until mid-January

**Comment by napulen** [comment]
Yes, the repo is currently private because of an ongoing academic peer-review process. When that concludes, I'll reopen the PR.

**Comment by erezsh** [comment]
Great. Good luck!

**Comment by napulen** [comment]
Peer-review process is done now :). Link is working again.

**Comment by erezsh** [comment]
Done.

You should post your project on reddit or hackernews, maybe you'll get a few users.

**Comment by napulen** [comment]
That's a great idea. Thanks!

**Pull request merged**
