### PR TITLE
Added strict-mode, enabled using the strict=True flag

### PR DESCRIPTION
**Pull request by erezsh**

### CODE REVIEW

**Review by MegaIng — APPROVED** [review]
Looks good, a few more tests might be nice.

For a future PR, it might be nice to transform `LarkOptions` and the two `Config` classes into `dataclasses`. Would remove some code duplication

**Comment by erezsh** [comment]
Definitely, I'm going to add some tests.

Sure, I'm pro dataclasses. But they have to be backported for Python 3.6.

**Comment by MegaIng** [comment]
There is such a backport, I am using it in `interegular`.

**Comment by erezsh** [comment]
Yes, I know. That's why I said I'm okay with it.

**Pull request merged**
