### PR TITLE
Support multiline regular expressions if they are marked with `x` (verbose) flag

### PR DESCRIPTION
**Pull request by decorator-factory**
Now you can do this:
```make
rule: /
      a     b  c d   # Foo bar baz 
     e   f  g h
     /x
```

### CODE REVIEW

**Comment by decorator-factory** [comment]
Implementation of https://github.com/lark-parser/lark/issues/300

**Comment by erezsh** [comment]
Looks good!

Just squash the first 3 commits together, and remove the unused import.

**Comment by decorator-factory** [comment]
I hope I didn't screw up during the rebase wizardry. It seems that I didn't.

**Comment by erezsh** [comment]
Looks good enough!

Thanks for the PR 👍

**Pull request merged**
