### PR TITLE
Add print parameter to lark.tools.standalone.main

### PR DESCRIPTION
**Pull request by rec**

### CODE REVIEW

**Comment by rec** [comment]
So you can call l.t.standalone.main() and capture the output.

**Comment by erezsh** [comment]
Nice idea, thanks!

**Comment by MegaIng** [comment]
Suggestion: rework tests. I will do this latter if noone else does.

**Comment by rec** [comment]
I'd be willing to add a test for this - why not?

There didn't seem to be tests covering this but it would be easy enough to write one now...

**Comment by erezsh** [comment]
Look in `lark\tests\test_tools.py`

**Pull request merged**
