### PR TITLE
Refactor load_grammar to use Terminal/NonTerminal throughout the process

### PR DESCRIPTION
**Pull request by erezsh**
It took a bit of refactoring, but I think I got it done without too many changes.

Maybe I'm missing something, but apparently it's not necessary to change mangle, aliases, or the rest.

### CODE REVIEW

**Comment by erezsh** [comment]
(I didn't move anything to a new module yet, so the diff will be easy to read)

**Comment by erezsh** [comment]
@MegaIng Looks like both the tests and I missed two glaring bugs in the refactor, so if you have the time to give it another look, it's probably a good idea.

Maybe it's impossible to catch everything. But I do wonder if there's a way to do it better, so we won't have to find them by "luck".

**Comment by erezsh** [comment]
@MegaIng You were right about %ignore. I guess coverage is good for something.

I also found another problem that was hidden for a long time.

**Comment by MegaIng** [comment]
Yeah, I can do that. Btw, do we want abnf as a default packaged grammar or as a plugin/example?

**Comment by erezsh** [comment]
I'm not sure. I'm a little worried about bloat, but maybe ABNF is standard enough to warrant being built-in.

What do you think?

**Comment by erezsh** [comment]
I don't see the harm in a few more tests and examples. But I agree additions to the actual library should be minimal.

**Pull request merged**
