### PR TITLE
Trivial Renamings for Readability

### PR DESCRIPTION
**Pull request by hf-kklein**

### CODE REVIEW

**Comment by erezsh** [comment]
Does it really make it more readable?

**Comment by hf-kklein** [comment]
Yeah, it's arguable whether `c`, `k` and `v` are necessary but imho the name `n` for a single child is not intuitive. We could cherry pick https://github.com/lark-parser/lark/pull/1104/commits/b815a927a24232624f55d8126fc9bcccd58cd3fe ?

**Comment by erezsh** [comment]
I agree `n` is a little out of character for the code-base. Just hard for me to imagine anyone getting confused there :)

But sure, cherry pick and force push it and I'll accept it.

**Comment by hf-kklein** [comment]
> But sure, cherry pick and force push it and I'll accept it.

#1110 

> Just hard for me to imagine anyone getting confused there :)

I just found it when running a linter on the code base. You're right. Confusion is already an exaggaration here ;)

**Pull request closed without merging**
