### PR TITLE
Add missing elements in standalone parser

### PR DESCRIPTION
**Pull request by BlankSpruce**
Add:
- missing imports
- missing `Enumerator` class
- missing `_serialize` function
- `__version__` variable

Additionally regenerated json parser example

### CODE REVIEW

**Comment by erezsh** [comment]
Why do you need to serialize from the Standalone parser?

**Comment by BlankSpruce** [comment]
Serialization might be still needed for multiprocessing purposes. That being said I'll check if, at least in my case, it could be somehow mitigated.

**Comment by BlankSpruce** [comment]
I've amended the change. Lack of `_serialize` method is not an issue which can't be easily mitigated. Thanks for hint.

**Comment by erezsh** [comment]
Thanks for the PR!

**Pull request merged**
