### PR TITLE
Lexer error recovery

### PR DESCRIPTION
**Pull request by evandrocoan**
Continuation from: https://github.com/lark-parser/lark/pull/236#issuecomment-423159458

### CODE REVIEW

**Comment by erezsh** [comment]
This seems like a reasonable patch. But, I'm not sure what's the benefit here?

What do you provide in on_error that won't cause a corrupted state in case of errors?

**Comment by erezsh** [comment]
In the same vein, a few unitests or an example would be very helpful

**Comment by evandrocoan** [comment]
I am working on it right now. First I had to figure out how to run a single unit test.
```shell
python -m unittest tests.test_parser.TestLalrStandard.test_lexer_error_recovering
```

**Comment by erezsh** [comment]
Just for the record, I just run the tests like this

    python -m tests

Or

    python -m tests TestClass.test_name

**Comment by erezsh** [comment]
Thanks for the test, but honestly I'm still not sure what is a practical way to use this feature.

Do you have an example (even tiny) that could be considered real-world error recovery?

**Comment by evandrocoan** [comment]
I was trying to get an example. I though it would be simple to find an example, but I also see no use for lexical error recovering. As long as I feel, I am very happy with lark as it is. I can only say parsing theory is very a hard subject, and requires a very hard study and understanding to write an good parser. Thank you very much for writing such marvelous parser with your free time. Sorry for wasting your time reviewing my code for this error recovering thing.

For now, I will be closing these pull requests for error recovering. If someday I really find some use for this error recovering, this code will be saved here for us to use and continue from it.

**Comment by erezsh** [comment]
No worries. You're right, it's a difficult subject!

I do have some ideas for error recovery, so perhaps I will try them when I have the time.

**Pull request closed without merging**
