### PR TITLE
Added tree_validator.py, which allows validating an AST against a grammar

### PR DESCRIPTION
**Pull request by erezsh**

### CODE REVIEW

**Comment by MegaIng** [comment]
The tests aren't being run.

**Comment by erezsh** [comment]
Should work now.

**Comment by MegaIng** [comment]
You a lot of TODO: ambiguity. What does this do with ambiguity?

**Comment by erezsh** [comment]
Well, if the grammar is ambiguous, there's more than one way to validate it. So to support it, we'll have to take every possible path.

(unless we can think of a more efficient way)

**Review by MegaIng — APPROVED** [review]
I would suggest adding an example, when possible with the python grammar and a relatively complex program as a stress test.

**Comment by erezsh** [comment]
Good idea, I did some more testing and figured out it's incorrect.

I might give it another go some day, maybe with a different approach.

**Pull request closed without merging**
