### PR TITLE
Postprocessor option for reconstruction

### PR DESCRIPTION
**Pull request by julienmalard**
Added possibility of a postprocessor to the reconstructor.

### CODE REVIEW

**Comment by julienmalard** [comment]
Hello,

Here is the pull request for adding reconstructor post-processors! As of now `reconstruct()` accepts a function as a postprocessor; would you prefer it to be a class with a `process` method, similarly to the postlexer option?

(I am not too sure why so many commits are appearing...I think I did something wrong in my rebase of my github fork. Apologies for that--I am still a bit new to git. Please do let me know if you know how I could fix it!)

-Julien

**Comment by erezsh** [comment]
I don't know, it's a bit of a mess.

Can you try to rebase your branch over `recons_work2` and the send a pull request? That might solve it.

**Comment by julienmalard** [comment]
Just tried rebasing... any better?
Very sorry about that.

**Comment by erezsh** [comment]
Don't know. I think I'll just copy-paste the change.

I'll be stealing your credit, so sorry about that ;)

**Comment by julienmalard** [comment]
Hello,

No problem! :) Thank you very much for your patience with my Git complications.

(By the way, I think I finally fixed it, if it helps for the next pull request.)

-Julien

**Pull request closed without merging**
