### PR TITLE
Better cache

### LINKED ISSUE #870: Make cache file more resilent
Currently grammar cache files that Lark creates can end up containing malformed data. It can happen as a result of:
1. Python version mismatches,
2. Truncated file in case of power loss, or python interpreter getting killed or interrupted in the middle of the write.
3. Simultaneous write from multiple threads / processes,

It can be solved by implementing the following:

1. Adding a suffix that indicates version of interpreter that created the cache file. I believe you'd need first 2 numbers from python version + interpreter type, e.g. cpython-3.8, pypy-3.5.

2. Making sure that contents of file are commited to disk and the cache file is atomically replaced. Here are approximate steps: a) create a temp file in the same dir as cache file (to make sure that the files are on the same filesystem). Python has a lib to work with temp files, b) after data is written to the file, do `f.flush()` to flush in-python buffer, and then `os.fsync(f)`. It'll make sure that contents are properly commited to disk, and not just pushed into OS-level RAM fs cache. Then do `os.rename` to replace the old cache file (if any?) with the new one. This op is usually atomic -- the file is either renamed or it's not.

3. Actually step 2) would already prevent data races from multithreaded writes since they'd write into different files, and rename is atomic. But it's possible to go futher and use file-based locks (e.g. filelock module) to make sure that only one process does all the compute, and all other processes idle until the cache is ready. Larger grammars can take tens of seconds to prepare, so it can add up, especially if lark is used in multithreaded/multiprocess server where grammar is loaded on init (20 processes, 30 seconds each -> 10 minutes of CPU time). I'm not sure that it's Lark responsibility though, and you may not want to add dependency on other packages.

### PR DESCRIPTION
**Pull request by MegaIng**
Should close #870 and #871

@alexandermorozov I hope this correctly addresses your concerns.

(especially the file verification was actually a lot simpler than I originally though. Although it isn't perfect (it doesn't detect changes to`common.lark` for example.))

### CODE REVIEW

**Comment by erezsh** [comment]
I like the idea of saving the list of dependencies in the cache!

Why won't it detect changes in common.lark ?

**Comment by erezsh** [comment]
Why would anyone ever set `safe_cache=False` ?

If you're not using any imports, `verify_used_files()` is a no-op. And if you are using them, you'd want to them checked.

If someone is really trying to minimize file reads, they'd be better off using the standalone parser, or manually save/load.

**Comment by MegaIng** [comment]
> Why won't it detect changes in common.lark ?

Because we are using `pkgutil.get_data` to support zip files. Supporting that as well is quite a bit more work (I am not even sure how we would do that).

> I like the idea of saving the list of dependencies in the cache!

Thank @alexandermorozov in #871.

**Comment by MegaIng** [comment]
> (I am not even sure how we would do that).

Ok, I just got an idea. Will try to implement

**Comment by erezsh** [comment]
@MegaIng 

`TypeError: 'override' is an invalid keyword argument for open()`

Did you mean overwrite?

**Pull request merged**
