### PR TITLE
Add rule renaming (and fix import bug)

### PR DESCRIPTION
**Pull request by Rogdham**
Following discussion in #148, this PR adds the syntax `%import .local.file.rule -> foobar` allowing to rename a rule while importing it.

While writing tests, I've encountered a bug: `%import .local.file.rule` internally renames the rule as `local.file.rule`, but this is not a valid group identifier for Python, which makes `lexer._build_mres` crash. I've changed so that the named rule is `local__file__rule` to avoid the issue.

Also added some more doc, tests, examples.

Please review carefully as I don't know your codebase, so I may have broken things inadvertently!

### CODE REVIEW

**Comment by erezsh** [comment]
Other than that it looks good!

**Comment by Rogdham** [comment]
> * All tests that perform relative imports should use a .lark file (see `test_relative_import`), so that it works with pytest and other test libraries.

Could you tell me what I should change? The tests performing relative imports that I wrote are using the `tests/grammars/ab.lark` file I believe.

> * The since you have several (4) files for the same example, it's better that you create a directory inside examples specifically for that example (or group of examples of the same sort).

I've edited my commit.

**Comment by erezsh** [comment]
For example `test_relative_import_rename`

**Comment by Rogdham** [comment]
> For example `test_relative_import_rename`

That test imports from the file `tests/grammars/test.lark` due to [this line](https://github.com/lark-parser/lark/pull/325/files#diff-ed9d66898a1188fc8f00f74cc941be36R1021):
`%import .grammars.test.NUMBER -> N`

I'm not sure I understand, could you tell me what I should do instead?

**Comment by erezsh** [comment]
Just put the string in a separate .lark file, and use _Lark_open, otherwise the relative import won't always be relative to the right directory

**Comment by Rogdham** [comment]
Oh I see now, like the code examples that have been pushed to `master` before I did this PR.

I tried to change that, and I have rebased on `master` as well, tell me what you think!

**Pull request merged**
