### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -L nd,iif,ot,datas`

### CODE REVIEW

**Review by erezsh — APPROVED** [review]
Yikes! Some of these have been there for a while!

**Comment by erezsh** [comment]
Thanks!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

Maybe adding a `codespell` pre-commit hook?

**Comment by erezsh** [comment]
Maybe!

**Comment by kianmeng** [comment]
Should I create a PR for this?

**Comment by erezsh** [comment]
Sure!

**Pull request merged**
