### PR TITLE
Update parse_tree_builder.py

### PR DESCRIPTION
**Pull request by jmishra01**
List function is not required, and rule check in callback dict should be after loop

### CODE REVIEW

**Comment by erezsh** [comment]
Hello! Thanks for the PR. You're right about moving the rule check up in the loop. But I prefer that you avoid changing lines only for cosmetic reasons, especially when it's very subjective, like removing blank lines that separate code blocks.

**Comment by jmishra01** [comment]
Revert changing lines changes.

**Comment by jmishra01** [comment]
@erezsh Thanks. Understood the reason behind calling `list()`. I'm closing this PR.

**Comment by erezsh** [comment]
@jmishra01 You can re-open with just the rule-check. I'll be happy to merge that in.

**Pull request closed without merging**
