### PR TITLE
Added ast_utils + example

### PR DESCRIPTION
**Pull request by erezsh**

### CODE REVIEW

**Comment by MegaIng** [comment]
I would suggest not forcing the user to use the `camel_to_snake` system. Also sometimes you might want one class for different nodes. I would suggest adding a `__init_subclass__` and a class level attribute/class level keyword argument to modify this.

**Comment by erezsh** [comment]
@MegaIng Rules are snake_case, so I can't see a situation when you would want to keep the caps.

You can do something like

```
class MultiPurposeNode(Ast): ...

usecase1 = MultiPurposeNode
usecase2 = MultiPurposeNode
usecase3 = MultiPurposeNode
usecase4 = MultiPurposeNode
```

It should work.

**Review by MegaIng — APPROVED** [review]

**Comment by erezsh** [comment]
(nothing changed, I just added the pyi file)

**Review by MegaIng — APPROVED** [review]

**Comment by MegaIng** [comment]
Btw, mypy throws errors, but the check still succeededs.

**Comment by erezsh** [comment]
I don't use mypy, I'm only adding the stubs as a courtesy for the users.

If you know how to fix the mypy errors, go ahead.

**Comment by MegaIng** [comment]
Well, we have a check setup here on github for type checking. If you look at the output, you see that mypy complains. But the check doesn't fail.

**Comment by MegaIng** [comment]
We are specifically ignoring these errors: https://github.com/lark-parser/lark/blob/eac537a434dd6b5d2145d147f8fd90aa0131a5db/.github/workflows/mypy.yml#L19

I think I will try to fix all the errors.

**Pull request merged**
