### PR TITLE
Blackened a lot of files

### PR DESCRIPTION
**Pull request by ThatXliner**
I used thee autoformatter [black]()

### CODE REVIEW

**Comment by ThatXliner** [comment]
three things:
I used black to format the files,
Isort to sort imports
and Sourcery to refactor code

**Comment by ThatXliner** [comment]
Hmm, But i'll need to fix the circular imports

**Comment by MegaIng** [comment]
Ok. Please change the max line length. We don't want unnecessarily split up lines. It makes the code harder to read.

If possible. split this PR up into multiple, each reformatting a specific part of the code/a specific rule.

**Comment by ThatXliner** [comment]
Should I remove the python 2.7 tests?

**Comment by MegaIng** [comment]
Not in this PR.

**Comment by ThatXliner** [comment]
I'm going to close this PR. There is much to undo

**Pull request closed without merging**
