### PR TITLE
Bump pre-commit hooks and add `codespell` hook

### PR DESCRIPTION
**Pull request by kianmeng**
As discussed https://github.com/lark-parser/lark/pull/1242

### CODE REVIEW

**Comment by erezsh** [comment]
Doesn't seem to be working.. I added a comment typo and ran `pre-commit run`, and codespell passes without any message.

```python
    source_path: Optional[str] # Sxmbol
```

**Comment by kianmeng** [comment]
Unfortunately, `codespell` don't contains that incorrect typo, `Sxmbol` in its [dictionary file](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt). Maybe because it's not that common, https://github.com/search?q=sxmbol&type=code.

If we change the incorrect typo to:

```python
>> 74     source_path: Optional[str] # Symbo
```

It work just fine, as shown:

```sh
$ pre-commit run --all-files
...
codespell................................................................Failed
- hook id: codespell
- exit code: 65

lark/lark.py:74: symbo ==> symbol
```

**Comment by erezsh** [comment]
Sorry for the delay. Thanks for contributing!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
