### PR TITLE
Postproc option for reconstruct, and fixed isalnum bug with unicode identifiers

### PR DESCRIPTION
**Pull request by julienmalard**

### CODE REVIEW

**Comment by erezsh** [comment]
Why not

```python
if post_proc:
    x = post_proc(x)
```
?

**Comment by erezsh** [comment]
Also, where can I find a list of all available categories? Python docs aren't being helpful.

**Comment by julienmalard** [comment]
@erezsh : Good idea! For the identifier unicode class categories, they are buried deep in a PEP from 2007: https://www.python.org/dev/peps/pep-3131/#specification-of-language-changes

**Comment by erezsh** [comment]
Thanks!

**Comment by julienmalard** [comment]
Thank you!

**Pull request merged**
