### PR TITLE
Reconstruct with unicode terminals (Based on #748)

### PR DESCRIPTION
**Pull request by erezsh**
@julienmalard Your test is failing. Can you tell me why?

I don't think I changed anything substantial.

### CODE REVIEW

**Comment by MegaIng** [comment]
For me it seems like the bug is simply not fixed. Maybe something in master broke it again (the behavior exactly matches the reported bug in the test comment.)

**Comment by MegaIng** [comment]
@erezsh I think you accidentally reverted the change at line 337 in file `load_grammar.py`.

**Comment by erezsh** [comment]
You're right. I removed the check for unicode in terminal names. I guess it wasn't really necessary in the first place.

**Comment by julienmalard** [comment]
@erezsh I think @MegaIng is right, and that the latest commit should do the trick!
Thanks, 
Julien

**Pull request merged**
