### PR TITLE
Add non-english charatcher support

### PR DESCRIPTION
**Pull request by midnio**

### CODE REVIEW

**Comment by erezsh** [comment]
That is incorrect.

Also, such a change has to come with tests, showing that it can match several languages, but nothing else.

**Comment by midnio** [comment]
May that dumb, but I don't know how to make unit tests.

**Comment by midnio** [comment]
Then I just updated the regex to match only 1 char.

**Comment by BTaskaya** [comment]
Are you serious ? LMAO

**Comment by erezsh** [comment]
@midnio Thank you for trying to help. I hope this won't dissuade you from contributing to open-source in the future, when you have improved your skills.

**Comment by midnio** [comment]
@erezsh Actually programming for 3 years (I'm 12-13 yo tho) but I'm still new to regex, that's normal :sweat_smile:

**Comment by midnio** [comment]
Then i'll try to implement it for myself first and open another pull request.

**Pull request closed without merging**
