### PR TITLE
Changed Lark standalone file extension from .g to .lark

### PR DESCRIPTION
**Pull request by RobRoseKnows**
- Commit `ca3d4ca` changed the extension from `.lrk` to `.lark` per discussion in Issue #116. 
- Reasoning addressed in Issue #116
- Renamed example and grammars file to use new extension.
- Changed `.g` to new extension of `.lark` in places where it is referenced.
- ~~Changed `.g` to new extension of `.lrk` in places where it is referenced.~~

### CODE REVIEW

**Comment by erezsh** [comment]
Looks good, thanks!

As you probably guessed, I'm waiting for the right time to merge it.

**Comment by RobRoseKnows** [comment]
Alright, I integrated the upstream changes you made into my branch so there should be no merge conflicts!

**Comment by erezsh** [comment]
Cool thanks

**Comment by erezsh** [comment]
Merged to branch 0.6.0

**Pull request merged**
